#!/bin/bash -e

BLUE='\E[1;34m'
CYAN='\E[1;36m'
YELLOW='\E[1;33m'
GREEN='\E[1;32m'
RESET='\E[0m'

echo -e "${BLUE}❯ ${CYAN}Building OpenResty ${YELLOW}${OPENRESTY_VERSION} with nginx_http_geoip2 module...${RESET}"
apt-get update
apt-get install -y \
    libtool \
    autoconf \
    automake \
    autotools-dev \
    build-essential \
        gcc \
        g++ \
        make \
        socat \
        git \
        libxml2 \
        libxml2-dev \
        libcurl4-openssl-dev \
        libyajl-dev \
        pkgconf \
        liblua5.1-dev \
        libpcre3-dev \
        libgeoip-dev \
        libssl-dev \
#    && /tmp/install-lua \
#    && /tmp/install-openresty \
apt-get clean


cd /tmp
wget "https://openresty.org/download/openresty-${OPENRESTY_VERSION}.tar.gz"
tar -xzf openresty-${OPENRESTY_VERSION}.tar.gz
mv /tmp/openresty-${OPENRESTY_VERSION} /tmp/openresty

git clone https://github.com/leev/ngx_http_geoip2_module.git
mv /tmp/ngx_http_geoip2_module /tmp/openresty/ngx_http_geoip2_module

cd /tmp
git clone --recursive https://github.com/owasp-modsecurity/ModSecurity ModSecurity
cd ModSecurity
git submodule init
git submodule update

./build.sh
./configure
make
make install

rm -rf /tmp/ModSecurity

cd /tmp
git clone https://github.com/owasp-modsecurity/ModSecurity-nginx


cd /tmp/openresty

./configure \
	--prefix=/etc/nginx \
	--sbin-path=/usr/sbin/nginx \
	--modules-path=/usr/lib/nginx/modules \
	--conf-path=/etc/nginx/nginx.conf \
	--error-log-path=/var/log/nginx/error.log \
	--http-log-path=/var/log/nginx/access.log \
	--pid-path=/var/run/nginx.pid \
	--lock-path=/var/run/nginx.lock \
	--http-client-body-temp-path=/var/cache/nginx/client_temp \
	--http-proxy-temp-path=/var/cache/nginx/proxy_temp \
	--http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
	--http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
	--http-scgi-temp-path=/var/cache/nginx/scgi_temp \
	--user=nginx \
	--group=nginx \
	--with-compat \
	--with-threads \
	--with-http_addition_module \
	--with-http_auth_request_module \
	--with-http_dav_module \
	--with-http_flv_module \
	--with-http_gunzip_module \
	--with-http_gzip_static_module \
	--with-http_mp4_module \
	--with-http_random_index_module \
	--with-http_realip_module \
	--with-http_secure_link_module \
	--with-http_slice_module \
	--with-http_ssl_module \
	--with-http_stub_status_module \
	--with-http_sub_module \
	--with-http_v2_module \
	--with-mail \
	--with-mail_ssl_module \
	--with-stream \
	--with-stream_realip_module \
	--with-stream_ssl_module \
	--with-stream_ssl_preread_module \
	--add-dynamic-module=/tmp/openresty/ngx_http_geoip2_module \
        --add-dynamic-module=/tmp/ModSecurity-nginx

make -j2

echo -e "${BLUE}❯ ${GREEN}OpenResty build completed${RESET}"
